hub:
  image:
    name: "qcdis/k8s-jhub"
  extraConfig:
    templates: |
      c.JupyterHub.template_paths = ['/etc/jupyterhub/custom/templates']
  concurrentSpawnLimit: 20
  consecutiveFailureLimit: 20
  activeServerLimit: 20
  namedServerLimitPerUser: 1
  shutdownOnLogout: true
  extraEnv:
    OAUTH_TLS_VERIFY: "0"
  baseUrl: /naavre-jupyterhub-custom
  config:
    GenericOAuthenticator:
      client_id: naavre
      client_secret: fake_openid_client_secret
      authorize_url: https://naavre-dev.minikube.test/auth/realms/vre/protocol/openid-connect/auth
      token_url: https://naavre-dev.minikube.test/auth/realms/vre/protocol/openid-connect/token
      userdata_url: https://naavre-dev.minikube.test/auth/realms/vre/protocol/openid-connect/userinfo
      oauth_callback_url: https://naavre-dev.minikube.test/naavre-jupyterhub-custom/hub/oauth_callback
      login_service: keycloak
      username_key: preferred_username
      userdata_params:
        state: state
      allowed_groups:
        - users
      admin_groups:
        - admins
    JupyterHub:
      authenticator_class: generic-oauth
      tls_verify: false
ingress:
  enabled: true
  hosts:
    - naavre-dev.minikube.test
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/add-base-url: "true"
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "600m"
    nginx.org/client-max-body-size: "600m"
proxy:
  service:
    type: ClusterIP
prePuller:
  continuous:
    enabled: false
  hook:
    enabled: false
singleuser:
  cmd: ['/usr/local/bin/start-jupyter-venv.sh']
  extraFiles:
    jupyter_notebook_config.json:
      mountPath: /etc/jupyter/jupyter_notebook_config.json
      data:
        ServerApp:
          iopub_data_rate_limit: 1.0e10
          iopub_msg_rate_limitFloat: 3000
  lifecycleHooks:
    postStart:
      exec:
        command: ["sh", "-c", "/tmp/init_script.sh"]
  defaultUrl: "/lab"
  extraEnv:
    BASE_IMAGE_TAGS_URL: https://github.com/QCDIS/NaaVRE-flavors/releases/download/v0.16/base_image_tags.json
    JUPYTERHUB_SINGLEUSER_APP: "jupyter_server.serverapp.ServerApp"
    MODULE_MAPPING_URL: https://raw.githubusercontent.com/QCDIS/NaaVRE-conf/main/module_mapping.json
    NAAVRE_API_TOKEN: ""
    SEARCH_API_ENDPOINT: ""
    SEARCH_API_TOKEN: ""
    VLAB_SLUG: n-a-a-vre
    API_ENDPOINT: https://lifewatch.lab.uvalight.net/vre-api
    MULTIPLY_CONF_URL: https://github.com/QCDIS/data-access/raw/master/multiply.zip
    CELL_GITHUB: https://github.com/QCDIS/NaaVRE-cells-test-2
    CELL_GITHUB_TOKEN: ""
    PROJ_LIB: /venv/share/proj
    ARGO_WF_SPEC_SERVICEACCOUNT: executor
    VRE_API_VERIFY_SSL: 'false'
  image:
    name: qcdis/n-a-a-vre
    tag: latest
    pullPolicy: IfNotPresent
